# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.gdzce.cn:
    container_name: orderer.gdzce.cn
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/gdzce.cn/orderers/orderer.gdzce.cn/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/gdzce.cn/orderers/orderer.gdzce.cn/tls/:/var/hyperledger/orderer/tls
        - orderer.gdzce.cn:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  node1.organization1.gdzce.cn:
    container_name: node1.organization1.gdzce.cn
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=node1.organization1.gdzce.cn
      - CORE_PEER_ADDRESS=node1.organization1.gdzce.cn:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=node1.organization1.gdzce.cn:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=node2.organization1.gdzce.cn:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=node1.organization1.gdzce.cn:7051
      - CORE_PEER_LOCALMSPID=Organization1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/organization1.gdzce.cn/peers/node1.organization1.gdzce.cn/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/organization1.gdzce.cn/peers/node1.organization1.gdzce.cn/tls:/etc/hyperledger/fabric/tls
        - node1.organization1.gdzce.cn:/var/hyperledger/production
    ports:
      - 7051:7051

  node2.organization1.gdzce.cn:
    container_name: node2.organization1.gdzce.cn
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=node2.organization1.gdzce.cn
      - CORE_PEER_ADDRESS=node2.organization1.gdzce.cn:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=node2.organization1.gdzce.cn:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=node2.organization1.gdzce.cn:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=node1.organization1.gdzce.cn:7051
      - CORE_PEER_LOCALMSPID=Organization1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/organization1.gdzce.cn/peers/node2.organization1.gdzce.cn/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/organization1.gdzce.cn/peers/node2.organization1.gdzce.cn/tls:/etc/hyperledger/fabric/tls
        - node2.organization1.gdzce.cn:/var/hyperledger/production

    ports:
      - 8051:8051

  node1.organization2.gdzce.cn:
    container_name: node1.organization2.gdzce.cn
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=node1.organization2.gdzce.cn
      - CORE_PEER_ADDRESS=node1.organization2.gdzce.cn:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=node1.organization2.gdzce.cn:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=node1.organization2.gdzce.cn:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=node2.organization2.gdzce.cn:10051
      - CORE_PEER_LOCALMSPID=Organization2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/organization2.gdzce.cn/peers/node1.organization2.gdzce.cn/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/organization2.gdzce.cn/peers/node1.organization2.gdzce.cn/tls:/etc/hyperledger/fabric/tls
        - node1.organization2.gdzce.cn:/var/hyperledger/production
    ports:
      - 9051:9051

  node2.organization2.gdzce.cn:
    container_name: node2.organization2.gdzce.cn
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=node2.organization2.gdzce.cn
      - CORE_PEER_ADDRESS=node2.organization2.gdzce.cn:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=node2.organization2.gdzce.cn:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=node2.organization2.gdzce.cn:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=node1.organization2.gdzce.cn:9051
      - CORE_PEER_LOCALMSPID=Organization2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/organization2.gdzce.cn/peers/node2.organization2.gdzce.cn/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/organization2.gdzce.cn/peers/node2.organization2.gdzce.cn/tls:/etc/hyperledger/fabric/tls
        - node2.organization2.gdzce.cn:/var/hyperledger/production
    ports:
      - 10051:10051

  node1.organization3.gdzce.cn:
    container_name: node1.organization3.gdzce.cn
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=node1.organization3.gdzce.cn
      - CORE_PEER_ADDRESS=node1.organization3.gdzce.cn:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=node1.organization3.gdzce.cn:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=node1.organization3.gdzce.cn:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=node2.organization3.gdzce.cn:12051
      - CORE_PEER_LOCALMSPID=Organization3MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/organization3.gdzce.cn/peers/node1.organization3.gdzce.cn/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/organization3.gdzce.cn/peers/node1.organization3.gdzce.cn/tls:/etc/hyperledger/fabric/tls
      - node1.organization3.gdzce.cn:/var/hyperledger/production
    ports:
      - 11051:11051

  node2.organization3.gdzce.cn:
    container_name: node2.organization3.gdzce.cn
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=node2.organization3.gdzce.cn
      - CORE_PEER_ADDRESS=node2.organization3.gdzce.cn:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=node2.organization3.gdzce.cn:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=node2.organization3.gdzce.cn:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=node1.organization3.gdzce.cn:11051
      - CORE_PEER_LOCALMSPID=Organization3MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/organization3.gdzce.cn/peers/node2.organization3.gdzce.cn/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/organization3.gdzce.cn/peers/node2.organization3.gdzce.cn/tls:/etc/hyperledger/fabric/tls
      - node2.organization3.gdzce.cn:/var/hyperledger/production
    ports:
      - 12051:12051
