# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.gdzce.cn:
  node1.organization1.gdzce.cn:
  node2.organization1.gdzce.cn:
  node1.organization2.gdzce.cn:
  node2.organization2.gdzce.cn:
  node1.organization3.gdzce.cn:
  node2.organization3.gdzce.cn:

networks:
  byfn:

services:

  orderer.gdzce.cn:
    extends:
      file: base/docker-compose-base.yaml
      service: orderer.gdzce.cn
    container_name: orderer.gdzce.cn
    networks:
      - byfn

  node1.organization1.gdzce.cn:
    container_name: node1.organization1.gdzce.cn
    extends:
      file: base/docker-compose-base.yaml
      service: node1.organization1.gdzce.cn
    networks:
      - byfn

  node2.organization1.gdzce.cn:
    container_name: node2.organization1.gdzce.cn
    extends:
      file: base/docker-compose-base.yaml
      service: node2.organization1.gdzce.cn
    networks:
      - byfn

  node1.organization2.gdzce.cn:
    container_name: node1.organization2.gdzce.cn
    extends:
      file: base/docker-compose-base.yaml
      service: node1.organization2.gdzce.cn
    networks:
      - byfn

  node2.organization2.gdzce.cn:
    container_name: node2.organization2.gdzce.cn
    extends:
      file: base/docker-compose-base.yaml
      service: node2.organization2.gdzce.cn
    networks:
      - byfn

  node1.organization3.gdzce.cn:
    container_name: node1.organization3.gdzce.cn
    extends:
      file: base/docker-compose-base.yaml
      service: node1.organization3.gdzce.cn
    networks:
      - byfn

  node2.organization3.gdzce.cn:
    container_name: node2.organization3.gdzce.cn
    extends:
      file: base/docker-compose-base.yaml
      service: node2.organization3.gdzce.cn
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=syschannel
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=node1.organization1.gdzce.cn:7051
      - CORE_PEER_LOCALMSPID=Organization1MSP
      # - CORE_PEER_TLS_ENABLED=true
      # - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/organization1.gdzce.cn/peers/node1.organization1.gdzce.cn/tls/server.crt
      # - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/organization1.gdzce.cn/peers/node1.organization1.gdzce.cn/tls/server.key
      # - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/organization1.gdzce.cn/peers/node1.organization1.gdzce.cn/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/organization1.gdzce.cn/users/Admin@organization1.gdzce.cn/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.gdzce.cn
      - node1.organization1.gdzce.cn
      - node2.organization1.gdzce.cn
      - node1.organization2.gdzce.cn
      - node2.organization2.gdzce.cn
      - node1.organization3.gdzce.cn
      - node2.organization3.gdzce.cn
    networks:
      - byfn
